---
title: Golang -- Tips (39)
---

recover()函数可以用于获取/拦截panic。仅当在一个defer函数中被完成时，调用recover()将会完成这个小技巧。

错误代码：
```
package main

import "fmt"

func main() {
    recover() // doesn't do anything
    panic("not good")
    recover() // won't be executed
    fmt.Println("ok")
}
```

正确代码：
```
package main

import "fmt"

func main() {
    defer func() {
        fmt.Println("recovered:", recover())
    }()
    panic("not good")
}
```

recover()的调用仅当它在defer函数中被直接调用时才有效。

错误代码：
```
package main

import "fmt"

func doRecover() {
    fmt.Println("recovered =>", recover()) //prints: recovered => <nil>
}
func main() {
    defer func() {
        doRecover() //panic is not recovered
    }()
    panic("not good")
}

```
